# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
ui:
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  results_on_new_tab: false
  search_on_category_select: true
  url_formatting: "pretty"
valkey:
  url: valkey://valkey:6379/0
categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  music:
  it:
  science:
  files:
  social media:
search:
  safe_search: 0
  autocomplete: "google"
  formats:
  - html # for browser
  - json # for openwebui and other apis
  - csv # for data analysis (because why not)